/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.telas;

import java.awt.Color;
import javax.swing.JOptionPane;
import br.com.bancoDeDados.Conectar_com_banco_de_dadaos;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Reinaldo Santos
 */
public class Tela_principal extends javax.swing.JFrame {

    TelaCliente Cliente = new TelaCliente();
    TelaFuncionario funcionario = new TelaFuncionario();
    TelaAutomóvel automovel = new TelaAutomóvel();
    TelaLocacao locacao = new TelaLocacao();

    /**
     * Creates new form Tela_principal
     */
    public Tela_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeDoUsuario = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        jLabelCargo = new javax.swing.JLabel();
        jLabelData1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuItemAtomovel = new javax.swing.JMenuItem();
        jMenuVeiculo = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuOpcao = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabelNomeDoUsuario.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelNomeDoUsuario.setForeground(new java.awt.Color(0, 0, 102));
        jLabelNomeDoUsuario.setText("Usuario");

        jLabelData.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(0, 0, 102));
        jLabelData.setText("Data");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagens/aluguel-de-carro3.png"))); // NOI18N

        jLabel11.setText("Reinaldo C Santos");

        desktop.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(850, Short.MAX_VALUE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelCargo.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelCargo.setForeground(new java.awt.Color(0, 0, 102));
        jLabelCargo.setText("Cargo: ");

        jLabelData1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelData1.setForeground(new java.awt.Color(0, 0, 102));
        jLabelData1.setText("Data:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagens/fundoTelaprin.gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenuCadastro.setText("Castastrar");

        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCliente);

        jMenuItemFuncionario.setText("Funcionário");
        jMenuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemFuncionario);

        jMenuItemAtomovel.setText("Automovel");
        jMenuItemAtomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtomovelActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemAtomovel);

        jMenuBar1.add(jMenuCadastro);

        jMenuVeiculo.setText("Locar veículo");

        jMenuItem2.setText("Locar carro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuVeiculo.add(jMenuItem2);

        jMenuBar1.add(jMenuVeiculo);

        jMenuOpcao.setText("Opção");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuOpcao.add(jMenuItemSair);

        jMenuBar1.add(jMenuOpcao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeDoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelData1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(1000, 1000, 1000)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelCargo)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelNomeDoUsuario)
                        .addGap(51, 51, 51)
                        .addComponent(jLabelData1)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelData)
                        .addGap(231, 231, 231)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktop))
                .addGap(19, 19, 19))
        );

        setSize(new java.awt.Dimension(1406, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/YYYY\n H:m");
        // DateFormat formatador = DateFormat.getDateInstance().getDateInstance(DateFormat.WEEK_OF_MONTH_FIELD);
        jLabelData.setText(formatador.format(data));

    }//GEN-LAST:event_formWindowActivated

    private void jMenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioActionPerformed
        // As linhas abaixo ira abrir a tela usuário dentro do desktopane
        automovel.dispose();
        Cliente.dispose();
        locacao.dispose();
        funcionario.setVisible(true);
        desktop.add(funcionario);
    }//GEN-LAST:event_jMenuItemFuncionarioActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        // TODO add your handling code here:
        automovel.dispose();
        locacao.dispose();
        funcionario.dispose();
        Cliente.setVisible(true);
        desktop.add(Cliente);

    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemAtomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtomovelActionPerformed
        // TODO add your handling code here:
        Cliente.dispose();
        locacao.dispose();
        funcionario.dispose();
        automovel.setVisible(true);
        desktop.add(automovel);
    }//GEN-LAST:event_jMenuItemAtomovelActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        automovel.dispose();
        Cliente.dispose();
        funcionario.dispose();
        locacao.setVisible(true);
        desktop.add(locacao);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabelCargo;
    public static javax.swing.JLabel jLabelData;
    public static javax.swing.JLabel jLabelData1;
    public static javax.swing.JLabel jLabelNomeDoUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JMenuItem jMenuItemAtomovel;
    public static javax.swing.JMenuItem jMenuItemCliente;
    public static javax.swing.JMenuItem jMenuItemFuncionario;
    public static javax.swing.JMenuItem jMenuItemSair;
    public static javax.swing.JMenu jMenuOpcao;
    public static javax.swing.JMenu jMenuVeiculo;
    // End of variables declaration//GEN-END:variables
}
